import { Octokit } from '@octokit/rest';

/**
 * Shared storage for contact-form submissions.
 *
 * Persists messages to src/data/contactMessages.ts in the repo (read by the
 * admin panel). Used by both /api/contact-submit (public, gated) and
 * /api/admin/contact-messages (admin CRUD). Reuses the same GITHUB_* config as
 * the other admin API routes.
 */

export interface ContactMessage {
  id: string;
  name: string;
  email: string;
  phone: string;
  projectType: string;
  budget?: string;
  timeline: string;
  message: string;
  attachments?: string[];
  submittedAt: string;
  status: 'new' | 'read' | 'responded' | 'archived' | 'spam';
  source?: string;
  /** Why the spam gate quarantined this message (only set when status = 'spam'). */
  spamReason?: string;
  notes?: string;
}

interface RepoConfig {
  token: string;
  owner: string;
  repo: string;
  branch: string;
  filePath: string;
}

function getConfig(): RepoConfig {
  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    throw new Error('GitHub token not configured');
  }
  return {
    token,
    owner: process.env.GITHUB_OWNER || 'DamianKaizhen',
    repo: process.env.GITHUB_REPO || 'Yudezign-Site-1',
    branch: process.env.GITHUB_BRANCH || 'main',
    filePath: 'src/data/contactMessages.ts',
  };
}

export async function getContactMessages(): Promise<ContactMessage[]> {
  const { token, owner, repo, branch, filePath } = getConfig();
  const octokit = new Octokit({ auth: token });

  const { data } = await octokit.repos.getContent({ owner, repo, path: filePath, ref: branch });
  if (!('content' in data)) {
    throw new Error('File not found');
  }

  const content = Buffer.from(data.content, 'base64').toString('utf-8');
  const arrayMatch = content.match(
    /export const contactMessages: ContactMessage\[\] = \[([\s\S]*?)\];/
  );
  if (!arrayMatch) {
    throw new Error('Could not parse contactMessages array');
  }

  try {
    // The stored file is generated by this module, so this is trusted content.
    return eval(`[${arrayMatch[1]}]`) as ContactMessage[];
  } catch (error) {
    console.error('Error parsing contactMessages:', error);
    throw new Error('Failed to parse contactMessages data');
  }
}

function escapeString(str: string): string {
  return str.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\r?\n/g, '\\n');
}

function formatMessage(m: ContactMessage): string {
  const lines: string[] = [
    `    id: '${m.id}',`,
    `    name: '${escapeString(m.name)}',`,
    `    email: '${escapeString(m.email)}',`,
    `    phone: '${escapeString(m.phone)}',`,
    `    projectType: '${escapeString(m.projectType)}',`,
  ];
  if (m.budget) lines.push(`    budget: '${escapeString(m.budget)}',`);
  lines.push(`    timeline: '${escapeString(m.timeline)}',`);
  lines.push(`    message: '${escapeString(m.message)}',`);
  if (m.attachments && m.attachments.length > 0) {
    lines.push(`    attachments: [${m.attachments.map((u) => `'${escapeString(u)}'`).join(', ')}],`);
  }
  lines.push(`    submittedAt: '${m.submittedAt}',`);
  lines.push(`    status: '${m.status}',`);
  if (m.source) lines.push(`    source: '${escapeString(m.source)}',`);
  if (m.spamReason) lines.push(`    spamReason: '${escapeString(m.spamReason)}',`);
  if (m.notes) lines.push(`    notes: '${escapeString(m.notes)}',`);
  return `  {\n${lines.join('\n')}\n  }`;
}

function reconstructFile(messages: ContactMessage[]): string {
  const body = messages.map(formatMessage).join(',\n');
  return `import type { ContactMessage } from '../types';

export const contactMessages: ContactMessage[] = [
${body}
];
`;
}

export async function commitContactMessages(
  messages: ContactMessage[],
  commitMessage: string
): Promise<void> {
  const { token, owner, repo, branch, filePath } = getConfig();
  const octokit = new Octokit({ auth: token });

  const { data: fileData } = await octokit.repos.getContent({
    owner,
    repo,
    path: filePath,
    ref: branch,
  });
  if (!('sha' in fileData)) {
    throw new Error('Could not get file SHA');
  }

  await octokit.repos.createOrUpdateFileContents({
    owner,
    repo,
    path: filePath,
    message: commitMessage,
    content: Buffer.from(reconstructFile(messages)).toString('base64'),
    branch,
    sha: fileData.sha,
  });
}

export interface NewContactMessage {
  name: string;
  email: string;
  phone: string;
  projectType: string;
  budget?: string;
  timeline: string;
  message: string;
  attachments?: string[];
  source?: string;
  status?: ContactMessage['status'];
  spamReason?: string;
  submittedAt?: string;
}

/** Append a new message and commit. Returns the stored record. */
export async function addContactMessage(input: NewContactMessage): Promise<ContactMessage> {
  const messages = await getContactMessages();

  const newMessage: ContactMessage = {
    id: `msg_${Date.now()}_${Math.random().toString(36).substring(2, 9)}`,
    name: input.name,
    email: input.email,
    phone: input.phone,
    projectType: input.projectType,
    ...(input.budget ? { budget: input.budget } : {}),
    timeline: input.timeline,
    message: input.message,
    ...(input.attachments && input.attachments.length ? { attachments: input.attachments } : {}),
    submittedAt: input.submittedAt || new Date().toISOString(),
    status: input.status || 'new',
    ...(input.source ? { source: input.source } : {}),
    ...(input.spamReason ? { spamReason: input.spamReason } : {}),
  };

  messages.push(newMessage);

  const commitMessage =
    newMessage.status === 'spam'
      ? `Quarantine spam contact message from ${newMessage.name}`
      : `New contact message from ${newMessage.name}`;
  await commitContactMessages(messages, commitMessage);

  return newMessage;
}
